use_frameworks!

platform :ios, '11.0'

target 'AFExtensionLib_Example' do
  pod 'AFExtensionLib', :path => '../'
  
  #AutoLayout
  #pod 'SnapKit', '~> 5.0.1'

  pod 'SwifterSwift'
#  pod 'Localize-Swift'
  
  target 'AFExtensionLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
