use_frameworks!

platform :ios, '10.0'

target 'AFExtensionLib_Example' do
  pod 'AFExtensionLib', :path => '../'

  target 'AFExtensionLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
